name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release version
    runs-on: ubuntu-latest
    steps:
      - uses: auto-it/setup-auto@v1

      - uses: actions/checkout@v2.3.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Set up git user
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.email "ahytha@relaynetwork.com"
          git config --global user.name "Auto Release Agent"
      
      - name: Set up parameters
        run: |
          export DATE=$(date '+%Y-%m-%d')
          export TAG=$DATE-${GITHUB_SHA::7}
          echo "TAG=$TAG" >> $GITHUB_ENV
      
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TAG: ${{env.TAG}}
        run: |
          git tag $TAG
          git push origin --tags

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create Release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          codeartifact_domain: rn-packages-dev
          codeartifact_region: us-east-2
        working-directory: ./
        run: |
          auto release
